<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schemaDeTableTest" nsURI="http://www.example.org/schemaDeTableTest"
    nsPrefix="schemaDeTableTest">
  <eClassifiers xsi:type="ecore:EClass" name="Tableau">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnes" lowerBound="1"
        upperBound="-1" eType="#//Colonne" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne" eSuperTypes="../../Algo/model/algo.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
