<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schemaTable" nsURI="http://www.example.org/schemaTable" nsPrefix="schemaTable">
  <eClassifiers xsi:type="ecore:EClass" name="Tableau">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonneLignes" lowerBound="1"
        eType="#//Colonne"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnes" upperBound="-1"
        eType="#//Colonne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contraintes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appel" eType="#//AppelAlgo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="string"/>
    <eLiterals name="int" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppelAlgo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algo" lowerBound="1" eType="ecore:EClass ../../Algo/model/algo.ecore#//Algo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
